"""Create model Projects2

Revision ID: 513826680db0
Revises: cc6d2d36982b
Create Date: 2025-10-12 13:49:27.418081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513826680db0'
down_revision: Union[str, Sequence[str], None] = 'cc6d2d36982b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_project', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('badge', sa.Enum('УЧЕБНЫЙ', 'ЛИЧНЫЙ ПРОЕКТ', 'НА ЗАКАЗ', 'OPEN SOURCE', 'INDUSTRY', native_enum=False), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('long_description', sa.String(), nullable=False),
    sa.Column('highlights', sa.JSON(), nullable=False),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.Column('github_url', sa.String(length=200), nullable=True),
    sa.Column('demo_url', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('Завершен', 'Онлайн', 'В работе', 'Внедрен в производство', 'Онлайн на хосте заказчика', native_enum=False), nullable=False),
    sa.Column('complexity', sa.SmallInteger(), nullable=False),
    sa.Column('automation_level', sa.SmallInteger(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
