"""Initial

Revision ID: faafb5b47a1b
Revises: 
Create Date: 2025-10-12 21:35:44.838303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faafb5b47a1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_for_index', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('slogan', sa.String(length=50), nullable=False),
    sa.Column('about', sa.String(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('contacts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_project', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('badge', sa.Enum('УЧЕБНЫЙ', 'ЛИЧНЫЙ ПРОЕКТ', 'НА ЗАКАЗ', 'OPEN SOURCE', 'INDUSTRY', native_enum=False), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('long_description', sa.String(), nullable=False),
    sa.Column('highlights', sa.JSON(), nullable=False),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.Column('github_url', sa.String(length=200), nullable=True),
    sa.Column('demo_url', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('Завершен', 'Онлайн', 'В работе', 'Внедрен в производство', 'Онлайн на хосте заказчика', native_enum=False), nullable=False),
    sa.Column('complexity', sa.SmallInteger(), nullable=False),
    sa.Column('automation_level', sa.SmallInteger(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_project'),
    sa.UniqueConstraint('title')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.String(length=20), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('process', sa.JSON(), nullable=True),
    sa.Column('technologies', sa.JSON(), nullable=True),
    sa.Column('cta', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('highlight', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cta'),
    sa.UniqueConstraint('icon'),
    sa.UniqueConstraint('title')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'customer', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('services')
    op.drop_table('projects')
    op.drop_table('admin_profiles')
    # ### end Alembic commands ###
